services:
  Patients:
    image: "medicarecord:dev"
    build:
      target: development_build
      context: ./Patients
      dockerfile: Dockerfile
      cache_from:
        - "medicarecord:dev"
        - "medicarecord:latest"
        - "*"
      args:
        DJANGO_ENV: development
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "-Wd", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000
    env_file:
      - ./Patients/.env.dev
    depends_on:
      - db
  
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./Patients/.env.dev

volumes:
  postgres_data:
